name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install deps
        run: pip install flask pytest flake8 black

      - name: Run tests
        run: python -m pytest

      - name: Lint
        run: flake8 src/app/

      - name: Format check
        run: black --check .        